name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Masuk ke folder projek frontend di direktori projects
            cd /home/magentaadam/projects/portfolio-react # <--- Sesuaikan dengan path aslimu

            # Tarik kode terbaru dan update package
            git pull origin main
            npm install

            # Build ulang file statis Vite
            npm run build

            # Restart service PM2 frontend
            pm2 restart portfolio-react